.TH BIOLIBC 3
.SH NAME
.PP

BIOLIBC \- Library of high-performance low-level functions for
bioinformatics programming

.SH SYNOPSIS
.PP
.nf 
.na
#include <biolibc/bed.h>
#include <biolibc/biostring.h>
#include <biolibc/dsv.h>
#include <biolibc/gff.h>
#include <biolibc/plist.h>
#include <biolibc/sam.h>
#include <biolibc/sam-buff.h>
#include <biolibc/vcf.h>

cc program.c -lbiolibc
.ad
.fi

.SH "PURPOSE"

Biolibc is a library of fast, memory-efficient, low-level functions for
processing biological data.

Like libc, it consists of numerous disparate, general-purpose functions
which could be used by a wide variety of applications.

These include functions for streaming common file formats such as SAM and
VCF, string functions specific to bioinformatics, etc.

Documentation on individual functions should be available soon.

.SH "SEE ALSO"
vcf-split, ad2vcf, vcf2hap, peak-classifier

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
