
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator macros for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_align_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-align-mutators.c */
int bl_align_set_min_match(bl_align_t *bl_align_ptr, size_t new_min_match);
int bl_align_set_max_mismatch_percent(bl_align_t *bl_align_ptr, unsigned new_max_mismatch_percent);
