
#ifndef _biolibc_h_
#include "biolibc.h"
#endif

typedef struct
{
    char    *desc,
	    *seq,
	    *plus,
	    *qual;
    size_t  desc_array_size,
	    seq_array_size,
	    plus_array_size,
	    qual_array_size,
	    desc_len,
	    seq_len,
	    plus_len,
	    qual_len;
}   bl_fastq_t;

#define BL_FASTQ_INIT           { NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0 }

// Must be same as BL_FASTA_LINE_UNLIMITED
#define BL_FASTQ_LINE_UNLIMITED 0

/*
 *  Generated by /home/bacon/scripts/gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_fastq_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_FASTQ_DESC(ptr)              ((ptr)->desc)
#define BL_FASTQ_DESC_AE(ptr,c)         ((ptr)->desc[c])
#define BL_FASTQ_SEQ(ptr)               ((ptr)->seq)
#define BL_FASTQ_SEQ_AE(ptr,c)          ((ptr)->seq[c])
#define BL_FASTQ_PLUS(ptr)              ((ptr)->plus)
#define BL_FASTQ_PLUS_AE(ptr,c)         ((ptr)->plus[c])
#define BL_FASTQ_QUAL(ptr)              ((ptr)->qual)
#define BL_FASTQ_QUAL_AE(ptr,c)         ((ptr)->qual[c])
#define BL_FASTQ_DESC_ARRAY_SIZE(ptr)   ((ptr)->desc_array_size)
#define BL_FASTQ_SEQ_ARRAY_SIZE(ptr)    ((ptr)->seq_array_size)
#define BL_FASTQ_PLUS_ARRAY_SIZE(ptr)   ((ptr)->plus_array_size)
#define BL_FASTQ_QUAL_ARRAY_SIZE(ptr)   ((ptr)->qual_array_size)
#define BL_FASTQ_DESC_LEN(ptr)          ((ptr)->desc_len)
#define BL_FASTQ_SEQ_LEN(ptr)           ((ptr)->seq_len)
#define BL_FASTQ_PLUS_LEN(ptr)          ((ptr)->plus_len)
#define BL_FASTQ_QUAL_LEN(ptr)          ((ptr)->qual_len)

/* fastq.c */
int bl_fastq_read(FILE *fastq_stream, bl_fastq_t *record);
int bl_fastq_write(FILE *fastq_stream, bl_fastq_t *record, size_t chars_per_line);
void bl_fastq_free(bl_fastq_t *record);
void bl_fastq_init(bl_fastq_t *record);

/* fastq-mutators.c */
int bl_fastq_set_desc(bl_fastq_t *bl_fastq_ptr, char *new_desc);
int bl_fastq_set_desc_ae(bl_fastq_t *bl_fastq_ptr, size_t c, char new_desc_element);
int bl_fastq_set_desc_cpy(bl_fastq_t *bl_fastq_ptr, char *new_desc, size_t array_size);
int bl_fastq_set_seq(bl_fastq_t *bl_fastq_ptr, char *new_seq);
int bl_fastq_set_seq_ae(bl_fastq_t *bl_fastq_ptr, size_t c, char new_seq_element);
int bl_fastq_set_seq_cpy(bl_fastq_t *bl_fastq_ptr, char *new_seq, size_t array_size);
int bl_fastq_set_plus(bl_fastq_t *bl_fastq_ptr, char *new_plus);
int bl_fastq_set_plus_ae(bl_fastq_t *bl_fastq_ptr, size_t c, char new_plus_element);
int bl_fastq_set_plus_cpy(bl_fastq_t *bl_fastq_ptr, char *new_plus, size_t array_size);
int bl_fastq_set_qual(bl_fastq_t *bl_fastq_ptr, char *new_qual);
int bl_fastq_set_qual_ae(bl_fastq_t *bl_fastq_ptr, size_t c, char new_qual_element);
int bl_fastq_set_qual_cpy(bl_fastq_t *bl_fastq_ptr, char *new_qual, size_t array_size);
int bl_fastq_set_desc_array_size(bl_fastq_t *bl_fastq_ptr, size_t new_desc_array_size);
int bl_fastq_set_seq_array_size(bl_fastq_t *bl_fastq_ptr, size_t new_seq_array_size);
int bl_fastq_set_plus_array_size(bl_fastq_t *bl_fastq_ptr, size_t new_plus_array_size);
int bl_fastq_set_qual_array_size(bl_fastq_t *bl_fastq_ptr, size_t new_qual_array_size);
int bl_fastq_set_desc_len(bl_fastq_t *bl_fastq_ptr, size_t new_desc_len);
int bl_fastq_set_seq_len(bl_fastq_t *bl_fastq_ptr, size_t new_seq_len);
int bl_fastq_set_plus_len(bl_fastq_t *bl_fastq_ptr, size_t new_plus_len);
int bl_fastq_set_qual_len(bl_fastq_t *bl_fastq_ptr, size_t new_qual_len);
