
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_fasta_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-fasta-mutators.c */
int bl_fasta_set_desc(bl_fasta_t *bl_fasta_ptr, char *new_desc);
int bl_fasta_set_desc_ae(bl_fasta_t *bl_fasta_ptr, size_t c, char new_desc_element);
int bl_fasta_set_desc_cpy(bl_fasta_t *bl_fasta_ptr, char *new_desc, size_t array_size);
int bl_fasta_set_seq(bl_fasta_t *bl_fasta_ptr, char *new_seq);
int bl_fasta_set_seq_ae(bl_fasta_t *bl_fasta_ptr, size_t c, char new_seq_element);
int bl_fasta_set_seq_cpy(bl_fasta_t *bl_fasta_ptr, char *new_seq, size_t array_size);
int bl_fasta_set_desc_array_size(bl_fasta_t *bl_fasta_ptr, size_t new_desc_array_size);
int bl_fasta_set_seq_array_size(bl_fasta_t *bl_fasta_ptr, size_t new_seq_array_size);
int bl_fasta_set_desc_len(bl_fasta_t *bl_fasta_ptr, size_t new_desc_len);
int bl_fasta_set_seq_len(bl_fasta_t *bl_fasta_ptr, size_t new_seq_len);
