    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_gff_index_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_GFF_INDEX_ARRAY_SIZE(ptr)    ((ptr)->array_size)
#define BL_GFF_INDEX_COUNT(ptr)         ((ptr)->count)
#define BL_GFF_INDEX_FILE_POS(ptr)      ((ptr)->file_pos)
#define BL_GFF_INDEX_FILE_POS_AE(ptr,c) ((ptr)->file_pos[c])
#define BL_GFF_INDEX_SEQID(ptr)         ((ptr)->seqid)
#define BL_GFF_INDEX_SEQID_AE(ptr,c)    ((ptr)->seqid[c])
#define BL_GFF_INDEX_START(ptr)         ((ptr)->start)
#define BL_GFF_INDEX_START_AE(ptr,c)    ((ptr)->start[c])
#define BL_GFF_INDEX_END(ptr)           ((ptr)->end)
#define BL_GFF_INDEX_END_AE(ptr,c)      ((ptr)->end[c])
