    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_gff_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_GFF_SEQUENCE(ptr)            ((ptr)->sequence)
#define BL_GFF_SEQUENCE_AE(ptr,c)       ((ptr)->sequence[c])
#define BL_GFF_SOURCE(ptr)              ((ptr)->source)
#define BL_GFF_SOURCE_AE(ptr,c)         ((ptr)->source[c])
#define BL_GFF_FEATURE(ptr)             ((ptr)->feature)
#define BL_GFF_FEATURE_AE(ptr,c)        ((ptr)->feature[c])
#define BL_GFF_START(ptr)               ((ptr)->start)
#define BL_GFF_END(ptr)                 ((ptr)->end)
#define BL_GFF_SCORE(ptr)               ((ptr)->score)
#define BL_GFF_STRAND(ptr)              ((ptr)->strand)
#define BL_GFF_PHASE(ptr)               ((ptr)->phase)
#define BL_GFF_ATTRIBUTES(ptr)          ((ptr)->attributes)
#define BL_GFF_ATTRIBUTES_AE(ptr,c)     ((ptr)->attributes[c])
#define BL_GFF_FEATURE_ID(ptr)          ((ptr)->feature_id)
#define BL_GFF_FEATURE_ID_AE(ptr,c)     ((ptr)->feature_id[c])
#define BL_GFF_GENE_NAME(ptr)           ((ptr)->gene_name)
#define BL_GFF_GENE_NAME_AE(ptr,c)      ((ptr)->gene_name[c])
