    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_gff3_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_GFF3_SEQID(ptr)               ((ptr)->seqid)
#define BL_GFF3_SEQID_AE(ptr,c)          ((ptr)->seqid[c])
#define BL_GFF3_SOURCE(ptr)              ((ptr)->source)
#define BL_GFF3_SOURCE_AE(ptr,c)         ((ptr)->source[c])
#define BL_GFF3_TYPE(ptr)                ((ptr)->type)
#define BL_GFF3_TYPE_AE(ptr,c)           ((ptr)->type[c])
#define BL_GFF3_START(ptr)               ((ptr)->start)
#define BL_GFF3_END(ptr)                 ((ptr)->end)
#define BL_GFF3_SCORE(ptr)               ((ptr)->score)
#define BL_GFF3_STRAND(ptr)              ((ptr)->strand)
#define BL_GFF3_PHASE(ptr)               ((ptr)->phase)
#define BL_GFF3_ATTRIBUTES(ptr)          ((ptr)->attributes)
#define BL_GFF3_ATTRIBUTES_AE(ptr,c)     ((ptr)->attributes[c])
#define BL_GFF3_ATTRIBUTES_ARRAY_SIZE(ptr) ((ptr)->attributes_array_size)
#define BL_GFF3_ATTRIBUTES_LEN(ptr)      ((ptr)->attributes_len)
#define BL_GFF3_FEATURE_ID(ptr)          ((ptr)->feature_id)
#define BL_GFF3_FEATURE_ID_AE(ptr,c)     ((ptr)->feature_id[c])
#define BL_GFF3_FEATURE_NAME(ptr)        ((ptr)->feature_name)
#define BL_GFF3_FEATURE_NAME_AE(ptr,c)   ((ptr)->feature_name[c])
#define BL_GFF3_FEATURE_PARENT(ptr)      ((ptr)->feature_parent)
#define BL_GFF3_FEATURE_PARENT_AE(ptr,c) ((ptr)->feature_parent[c])
#define BL_GFF3_FILE_POS(ptr)            ((ptr)->file_pos)
