
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_overlap_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-overlap-mutators.c */
int bl_overlap_set_feature1_len(bl_overlap_t *bl_overlap_ptr, int64_t new_feature1_len);
int bl_overlap_set_feature2_len(bl_overlap_t *bl_overlap_ptr, int64_t new_feature2_len);
int bl_overlap_set_overlap_start(bl_overlap_t *bl_overlap_ptr, int64_t new_overlap_start);
int bl_overlap_set_overlap_end(bl_overlap_t *bl_overlap_ptr, int64_t new_overlap_end);
int bl_overlap_set_overlap_len(bl_overlap_t *bl_overlap_ptr, int64_t new_overlap_len);
