    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_pos_list_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_POS_LIST_ARRAY_SIZE(ptr)     ((ptr)->array_size)
#define BL_POS_LIST_COUNT(ptr)          ((ptr)->count)
#define BL_POS_LIST_POSITIONS(ptr)      ((ptr)->positions)
#define BL_POS_LIST_POSITIONS_AE(ptr,c) ((ptr)->positions[c])
