
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_pos_list_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-pos-list-mutators.c */
int bl_pos_list_set_array_size(bl_pos_list_t *bl_pos_list_ptr, size_t new_array_size);
int bl_pos_list_set_count(bl_pos_list_t *bl_pos_list_ptr, size_t new_count);
int bl_pos_list_set_positions(bl_pos_list_t *bl_pos_list_ptr, int64_t *new_positions);
int bl_pos_list_set_positions_ae(bl_pos_list_t *bl_pos_list_ptr, size_t c, int64_t new_positions_element);
int bl_pos_list_set_positions_cpy(bl_pos_list_t *bl_pos_list_ptr, int64_t *new_positions, size_t array_size);
