    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_vcf_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_VCF_CHROM(ptr)               ((ptr)->chrom)
#define BL_VCF_CHROM_AE(ptr,c)          ((ptr)->chrom[c])
#define BL_VCF_ID(ptr)                  ((ptr)->id)
#define BL_VCF_ID_AE(ptr,c)             ((ptr)->id[c])
#define BL_VCF_REF(ptr)                 ((ptr)->ref)
#define BL_VCF_REF_AE(ptr,c)            ((ptr)->ref[c])
#define BL_VCF_ALT(ptr)                 ((ptr)->alt)
#define BL_VCF_ALT_AE(ptr,c)            ((ptr)->alt[c])
#define BL_VCF_QUAL(ptr)                ((ptr)->qual)
#define BL_VCF_QUAL_AE(ptr,c)           ((ptr)->qual[c])
#define BL_VCF_FILTER(ptr)              ((ptr)->filter)
#define BL_VCF_FILTER_AE(ptr,c)         ((ptr)->filter[c])
#define BL_VCF_INFO(ptr)                ((ptr)->info)
#define BL_VCF_INFO_AE(ptr,c)           ((ptr)->info[c])
#define BL_VCF_FORMAT(ptr)              ((ptr)->format)
#define BL_VCF_FORMAT_AE(ptr,c)         ((ptr)->format[c])
#define BL_VCF_SINGLE_SAMPLE(ptr)       ((ptr)->single_sample)
#define BL_VCF_SINGLE_SAMPLE_AE(ptr,c)  ((ptr)->single_sample[c])
#define BL_VCF_MULTI_SAMPLES(ptr)       ((ptr)->multi_samples)
#define BL_VCF_MULTI_SAMPLES_AE(ptr,c)  ((ptr)->multi_samples[c])
#define BL_VCF_POS(ptr)                 ((ptr)->pos)
#define BL_VCF_INFO_ARRAY_SIZE(ptr)     ((ptr)->info_array_size)
#define BL_VCF_INFO_LEN(ptr)            ((ptr)->info_len)
#define BL_VCF_FORMAT_ARRAY_SIZE(ptr)   ((ptr)->format_array_size)
#define BL_VCF_FORMAT_LEN(ptr)          ((ptr)->format_len)
#define BL_VCF_SINGLE_SAMPLE_ARRAY_SIZE(ptr) ((ptr)->single_sample_array_size)
#define BL_VCF_SINGLE_SAMPLE_LEN(ptr)   ((ptr)->single_sample_len)
#define BL_VCF_MULTI_SAMPLE_POINTER_ARRAY_SIZE(ptr) ((ptr)->multi_sample_pointer_array_size)
#define BL_VCF_MULTI_SAMPLE_COUNT(ptr)  ((ptr)->multi_sample_count)
#define BL_VCF_MULTI_SAMPLE_ARRAY_SIZES(ptr) ((ptr)->multi_sample_array_sizes)
#define BL_VCF_MULTI_SAMPLE_ARRAY_SIZES_AE(ptr,c) ((ptr)->multi_sample_array_sizes[c])
#define BL_VCF_MULTI_SAMPLE_LENS(ptr)   ((ptr)->multi_sample_lens)
#define BL_VCF_MULTI_SAMPLE_LENS_AE(ptr,c) ((ptr)->multi_sample_lens[c])
#define BL_VCF_REF_COUNT(ptr)           ((ptr)->ref_count)
#define BL_VCF_ALT_COUNT(ptr)           ((ptr)->alt_count)
#define BL_VCF_OTHER_COUNT(ptr)         ((ptr)->other_count)
#define BL_VCF_PHREDS(ptr)              ((ptr)->phreds)
#define BL_VCF_PHREDS_AE(ptr,c)         ((ptr)->phreds[c])
#define BL_VCF_PHRED_COUNT(ptr)         ((ptr)->phred_count)
#define BL_VCF_PHRED_BUFF_SIZE(ptr)     ((ptr)->phred_buff_size)
